##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file
#
##############################################################################
##############################################################################

name: PR Target Workflow
on:
  pull_request_target:

# Required for arkid15r/check-pr-issue-action
permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  PR-Greeting:
    name: Pull Request Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Add the PR Review Policy
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: pr_review_policy
          message: |
            ## Our Pull Request Approval Process

            This PR will be reviewed according to our:
            
            1. [Palisadoes Contributing Guidelines](https://developer.palisadoes.org/docs/contributor-guide/contributing) 
            
            2. [AI Usage Policy](https://developer.palisadoes.org/docs/contributor-guide/ai) 

            Thanks for contributing!

  Check-PR-Issue:
    name: Check Correct PR Issue Assignment
    runs-on: ubuntu-latest
    needs: [PR-Greeting]
    steps:
      - uses: actions/checkout@v4
      - name: Check PR linked issue and assignee
        uses: arkid15r/check-pr-issue-action@0.1.2
        with:
          close_pr_on_failure: 'true'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          no_assignee_message: |
              1. The linked issue must be assigned to the PR author. Please fill in our PR template correctly.
              1. Follow the GitHub [Linking a pull request to an issue](https://github.com/PalisadoesFoundation/talawa-plugin/pull/107) guide to correctly link an issue
          no_issue_message: |
              1. The PR must be linked to an issue assigned to the PR author.
              1. Follow the GitHub [Linking a pull request to an issue](https://github.com/PalisadoesFoundation/talawa-plugin/pull/107) guide to correctly link an issue
          check_issue_reference: 'true'
          require_assignee: 'true'
          # List of usernames who can create PRs without having an assigned issue
          skip_users_file_path: '.github/workflows/config/check-pr-issue-skip-usernames.txt'
